export const SERVER_ERROR_CODES = {
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
};

export const AUTH_TOKEN_ERROR_CODES = {
  BAD_TOKEN_ERROR: 'BAD_TOKEN_ERROR',
};

export const AUTH_ERROR_CODES = {
  WRONG_CREDENTIALS_ERROR: 'WRONG_CREDENTIALS_ERROR',
  USER_CREATE_VALIDATION_ERROR: 'USER_CREATE_VALIDATION_ERROR',
  USER_CREATE_ERROR: 'USER_CREATE_ERROR',
  FAILED_TO_RETRIVE_USER_INFO: 'ERROR_FAILED_TO_RETRIVE_USER_INFO',
};

export const LINK_ERROR_CODES = {
  FAILED_TO_RETRIVE_LINK_INFO: 'ERROR_FAILED_TO_RETRIVE_URL_INFO',
  URL_CREATE_VALIDATION_ERROR: 'URL_CREATE_VALIDATION_ERROR',
  URL_CREATE_ALREADY_EXIST_ERROR: 'URL_CREATE_ALREADY_EXIST_ERROR',
  URL_CREATE_ERROR: 'URL_CREATE_ERROR',
  URL_RENAME_ERROR: 'URL_RENAME_ERROR',
  URL_RENAME_ALREADY_EXIST_ERROR: 'URL_RENAME_ALREADY_EXIST_ERROR',
  URL_RENAME_NOT_EXIST_ERROR: 'URL_DELETE_NOT_EXIST_ERROR',
  URL_RENAME_FORBIDDEN: 'URL_RENAME_FORBIDDEN',
  URL_DELETE_ERROR: 'URL_DELETE_ERROR',
  URL_DELETE_NOT_EXIST_ERROR: 'URL_DELETE_NOT_EXIST_ERROR',
  URL_DELETE_FORBIDDEN: 'URL_DELETE_FORBIDDEN',
};
